USE ECOMMERCE; 

drop VIEW IF EXISTS ESTADO_OC_CANCEL;
drop VIEW IF EXISTS CLIENTES_CABA;
drop VIEW IF EXISTS PRODUCTOS_FALTA ;
drop VIEW IF EXISTS DEBITO_2023 ;
drop VIEW IF EXISTS OC_COMPLETA_CREDITO_2023;

CREATE VIEW ESTADO_OC_CANCEL AS (
SELECT ID_ORDEN, ESTADO, FECHA FROM ORDEN_COMPRA
WHERE ESTADO = "CANCELADA"
);

CREATE VIEW CLIENTES_CABA AS (
SELECT ID_CLIENTE, APELLIDO, EMAIL, LOCALIDAD FROM CLIENTE
WHERE LOCALIDAD = "CABA"
);

CREATE VIEW PRODUCTOS_FALTA AS (
SELECT ID_PRODUCTO, NOMBRE, CANTIDAD FROM PRODUCTO
WHERE CANTIDAD <= 30
ORDER BY CANTIDAD
);

CREATE VIEW DEBITO_2023 AS (
SELECT ID_METODO, DESCRIPCION, PRECIO, FECHA
FROM METODO_PAGO
WHERE DESCRIPCION = "DEBITO" AND FECHA >= "2023-01-01"
ORDER BY FECHA
);

CREATE VIEW  OC_COMPLETA_CREDITO_2023 AS (
SELECT ORDEN_COMPRA.ID_ORDEN, ORDEN_COMPRA.ESTADO, ORDEN_COMPRA.PRECIO, ORDEN_COMPRA.FECHA, METODO_PAGO.DESCRIPCION
FROM ORDEN_COMPRA, METODO_PAGO
WHERE METODO_PAGO.DESCRIPCION = "CREDITO" AND ORDEN_COMPRA.FECHA > "2023-01-01" AND ORDEN_COMPRA.ESTADO = "COMPLETA"
GROUP BY ID_ORDEN
);
