DROP SCHEMA IF EXISTS ECOMMERCE;
CREATE SCHEMA IF NOT exists ECOMMERCE;
USE ECOMMERCE;

CREATE TABLE CLIENTE (
ID_CLIENTE INT,
NOMBRE VARCHAR (20),
APELLIDO VARCHAR (50) NOT NULL,
EMAIL VARCHAR (50) NOT NULL,
CALLE VARCHAR (50) NOT NULL,
NUMERO INT NOT NULL,
LOCALIDAD VARCHAR (20) NOT NULL,
TEL INT NOT NULL,
PRIMARY KEY (ID_CLIENTE)
) ENGINE = InnoDB;

CREATE TABLE PRODUCTO (
ID_PRODUCTO INT,
NOMBRE VARCHAR (20) NOT NULL,
MODELO VARCHAR (20),
DESCRIPCION VARCHAR (500),
CANTIDAD INT NOT NULL,
PRECIO DECIMAL (50,2) NOT NULL,
PRIMARY KEY (ID_PRODUCTO)
) ENGINE = InnoDB;

CREATE TABLE ORDEN_COMPRA (
ID_ORDEN INT,
ID_CLIENTE INT,
ID_PRODUCTO INT,
ESTADO ENUM ('COMPLETA', 'EN PROCESO', 'CANCELADA') NOT NULL,
DOMICILIO VARCHAR (100) NOT NULL,
PRECIO DECIMAL (50,2) NOT NULL,
FECHA DATE NOT NULL,
PRIMARY KEY (ID_ORDEN),
CONSTRAINT fkID_CLIENTE_ORDEN foreign key (ID_CLIENTE) references CLIENTE (ID_CLIENTE),
CONSTRAINT fkID_PRODUCTO_ORDEN foreign key (ID_PRODUCTO) references PRODUCTO (ID_PRODUCTO)
) ENGINE = InnoDB;

CREATE TABLE CARRITO (
ID_CARRITO INT,
ID_PRODUCTO INT,
PRECIO DECIMAL (50,2) NOT NULL,
ESTADO ENUM ('COMPLETO', 'EN PROCESO', 'CANCELADO') NOT NULL,
FECHA DATE NOT NULL,
PRIMARY KEY (ID_CARRITO),
CONSTRAINT fkID_PRODUCTO_CARRITO foreign key (ID_PRODUCTO) references PRODUCTO (ID_PRODUCTO)
) ENGINE = InnoDB;

CREATE TABLE METODO_PAGO (
ID_METODO INT,
ID_CLIENTE INT,
ID_ORDEN INT,
DESCRIPCION ENUM ('DEBITO', 'CREDITO', 'CANCELADO') NOT NULL,
PRECIO DECIMAL (50,2) NOT NULL,
FECHA DATE NOT NULL,
PRIMARY KEY (ID_METODO),
CONSTRAINT fkID_CLIENTE_PAGO foreign key (ID_CLIENTE) references CLIENTE (ID_CLIENTE),
CONSTRAINT fkID_ORDEN_PAGO foreign key (ID_ORDEN) references ORDEN_COMPRA (ID_ORDEN)
) ENGINE = InnoDB;

